server:
  port: 9009
spring:
  application:
    name: search
  rabbitmq:
    host: 192.168.31.128
  redis:
    host: 192.168.31.128
  main:
    #当遇到同样名字的 时候，是否允许覆盖注册
    allow-bean-definition-overriding: true
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 192.168.31.128:9300

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      #配置全局的feign的调用超时时间 如果 有指定的服 务配置 默认的配置不会生效
      default:
        # 指定的是 消费者 连接服务提供者 的连接超时时间 是否能连接 单位是毫秒
        connectTimeout: 600000
        # 指定的是调用服务提供者的 服务 的 超时时间（） 单位是毫秒
        readTimeout: 600000

#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
        #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: false
        isolation:
          strategy: SEMAPHORE